### ISSUE TITLE
Dropdown input addon

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#295]
### С чем связан запрос на фичу?

Реализовать аддон dropdown для инпута:

![image](https://user-images.githubusercontent.com/62806448/121165211-87c6b500-c869-11eb-8dc0-b420ebcab404.png)

### Расскажите как вы это себе видите

Инпут заполняется в соответствии с выбранным в дропдауне значением

### Приложите примеры реализаций

https://material-ui.com/ru/components/autocomplete/

**Comment by TorinAsakura** [comment]
https://www.npmjs.com/package/downshift

**Comment by TorinAsakura** [comment]
https://github.com/atls/uikit/pull/302
