### ISSUE TITLE
Currency text addon

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#297]
### С чем связан запрос на фичу?

Реализовать аддон для Text ориентированный на отображение значений для валют (рубли, `$`)

### Расскажите как вы это себе видите

![image](https://user-images.githubusercontent.com/62806448/121171243-b051ad80-c86f-11eb-93ba-6761f1817e8e.png)

### Приложите примеры реализаций

https://github.com/YouThinkResearch/web/blob/dev/frontend/ui/text/src/Ruble.ts

**Comment by TorinAsakura** [comment]
У тебя есть компонент - сделай аддон для работы с юникод-символами

**Comment by TorinAsakura** [comment]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
