### ISSUE TITLE
Back Panel

### ISSUE THREAD

**Issue by dakand** [atls/uikit#319]
### С чем связан запрос на фичу?
Спроектировать интерфейс бэк-панели.

### Расскажите как вы это себе видите
С бэк панелью будут работать 3 типа пользователей: **Агент поддержки, Аналитик по фроду и начислениям, Оператор** ([подробнее](https://www.notion.so/252cc2144a7f4102959ad939416b3477#2d721288db8c443899dc1dd569b10e67)). Агент поддержки имеет наиболее широкий функционал, поэтому изначально при проектировании будут учитываться возможности агента поддержки. Структура бэк панели [здесь](https://www.figma.com/file/SC0ySy8GI26qcfRROYpNt4/Back-Panel?node-id=0%3A1). Необходимо спроектировать разделы по порядку:
- [x] Страница панелиста.
- [x] Главная (последние активности).
- [x] Поиск.
- [x] Запросы на выплаты.
- [x] Пользователи, функция добавления пользователей.
- [x] Аналитика фрода.
- [x] Сгруппировать все компоненты и фрагменты.
- [x] Написать Introduction, в котором описать структуру проекта в Figma, особенности ролей и некоторых разделов.

**Comment by TorinAsakura** [comment]
status?

**Comment by dakand** [comment]
Проект в [Figma](https://www.figma.com/file/ofuBEflZhwVbl3eGV9EXvv/Youthink-%7C-Back-Panel?node-id=238%3A5716).
