### ISSUE TITLE
Modification DreamTeam site

### ISSUE THREAD

**Issue by dakand** [atls/uikit#324]
### Какого рода задача?
Необходимо доработать сайт [DreamTeam](https://dream-team.tech/).

### Что и где будем менять?
[Проект в Figma](https://www.figma.com/file/OFpidYSscy6NOYWpRsfdwt/Dream-Team?node-id=0%3A1)
- [x] Доработать форму. 
- [x] Переработать страницу контактов.
- [x] Переработать страницу отзыва.
- [x] Добавить стили текста.
- [x] Переработать блок направлений.
- [x] Добавить анимированный фон и анимированные иконки. (Пункт необязателен, но планируется)

**Comment by TorinAsakura** [comment]
@dakand А что это за хуйн?

**Comment by dakand** [comment]
[Проект в Figma](https://www.figma.com/file/OFpidYSscy6NOYWpRsfdwt/Landing-Page?node-id=0%3A1) с результатом работы.
