### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#334]
## Research

1. Skeleton loader
Сейчас используется либа [react-content-loader](https://github.com/danilowoz/react-content-loader)
Проблема в том, что на каждую карточку приходится вручную создавать скелетон (и шейп скелетона никак не зависит от нее, так что в случае смены верстки у карточки придется вручную править скелетон)

2. Вынос Carousel в uikit. Требования:
- drag&swipe
- Цикличность
- Возможность крутить карусель с помощью кнопок (стрелок вправо/влево)

3. Вынос компонента Layer (ранее Modal) в uikit. [Пример](https://github.com/YouThinkResearch/web/tree/feature/dashboard/frontend/ui/layer) актуальной реализации
Реализация с порталом и onOutsideClick'ом довольно жирная, поэтому нужно вынести этот компонент в uikit. Используется для создания модалок и поповеров
4. Работа с хедерами в @atls/next-app-with-apollo. Сейчас в параметрах при инициализации провайдера есть поле headers, тип any[]. Когда хедеры попадают в провайдер с ними происходит [это](https://github.com/atls/nextjs/blob/master/packages/next-app-with-apollo/src/headers/extract.ts). Если так и должно быть - в таком случае не ясен принцип, какого вида функция должна быть на входе чтобы добавить заголовок

**Comment by TorinAsakura** [comment]
# 4
https://github.com/atls/nextjs/blob/3138f27f231c8f28f6dd4a5412b5b787f88ded12/packages/next-app-with-apollo/src/with-apollo.provider.tsx#L45

экстрактор, прикидывает контекст, а на выходе получает объект ключ значения хедеров

(ctx: NextCtx) => { [key: string]: string ]

**Comment by TorinAsakura** [comment]
# 1
## Варианты

## В рантайме
Компонент-обертка - компоненту закладывается какая-то схема, и он клонирует дочерний элемент и подставляет данные на основе этой схемы

## Генерация
Скрипт-генератор - берет на вход схему c компонентом и генерит компонент skeleton

## Типы или пропсы
Генерация на основе - типов или пропсов компонентов, имеем формат входных данных, пытаемся предугадать (что-то типа faker для конкретного поля) и строим схему, на основе которой генерим skeleton

**Comment by TFK70** [comment]
@TorinAsakura 

> В рантайме

Наиболее удобный и понятный, пока фаворит

> Генерация

В моем представлении эта реализация тащит за собой определенное количество оверхеда (по сравнению с первым вариантом):

1. Нужно будет самостоятельно описывать логику отображения скелетона используя Condition (верстка будет чуть более жирной и чуть менее читабельной)
2. Нужно будет дополнительно где-то хранить разметку скелетона
3. Нужно будет придумать как указывать скрипту таргеты для генерации скелетона, чтобы они вызывались автоматом на postinstall, например, как билд иконок

> Типы или пропсы

Здесь концепт не совсем понятен

1. Какой сущностью будет сам скелетон? (самостоятельный компонент, враппер поверх верстки, интерсептор (какой-нибудь HOC) и т.п.)
2. Как будут выглядеть входные данные для генерации скелетона?
3. Возможно ли будет более детально регулировать размеры стабов внутри скелетона? (например ширину плейсхолдера для строки, расстояние между ними и т.п.)

**Comment by TorinAsakura** [comment]
# 3
непонятно как layer и modal связаны вместе, если брать layer - то последнее время использую https://github.com/everweij/react-laag

если брать modal - то там ничего особо нет, те не усложняю, можно в каждом проекте писать отдельно, либо минималка как в архивном modal
