### ISSUE TITLE
Helmet for multi-page

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#340]
### С чем связан запрос на фичу?

Использовать шаблон Helmet элемента для все страниц внутри сервиса чтобы избежать дублирования кода

### Расскажите как вы это себе видите

Допустим есть сервис `dashboard`

Внутри дэшборда есть страницы `index`,`history`,`offers`
Для того чтобы инициализировать SEO каркас для каждой из страниц необходимо продублировать элемент следующего вида:

<details>

```javascript
import React      from 'react'
import { Helmet } from 'react-helmet'

export const Seo = () => {
  const title = 'title'
  const description = 'description'

  return (
    <Helmet
      htmlAttributes={{ lang: 'ru' }}
      title={title}
      titleTemplate={`%s | ${title}`}
      meta={[
        {
          name: 'description',
          content: description,
        },
        {
          property: 'og:title',
          content: title,
        },
        {
          property: 'og:description',
          content: description,
        },
        {
          property: 'og:type',
          content: 'website',
        },
        {
          name: 'twitter:card',
          content: 'summary',
        },
        {
          name: 'twitter:title',
          content: title,
        },
        {
          name: 'twitter:description',
          content: description,
        },
      ]}
    />
  )
}

```

</details>

## Проблема

Проблема в том, что этот элемент нужно создавать для каждой страницы отдельно, код дублируется

Пример проекта где этот элемент дублируется в страницах: https://github.com/torin-asakura/dream-team/tree/master/frontend/landing

**Comment by TorinAsakura** [comment]
Там можно тупо использовать стринги из месседжей. Так что можно использовать дефолтный шаблон хелмета
