### ISSUE TITLE
SEO&Accessability entity

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#352]
### С чем связан запрос на фичу?

Вынесение SEO/Accessability сущностей для компонента, в конечном итоге должно быть что-то типа plug'n'play

### Расскажите как вы это себе видите

На примере компонента Button:

Файлы `button.accessability.ts` и `button.seo.ts` с описанием accessability/seo сущностей

**Comment by TorinAsakura** [comment]
@TFK70 SEO пока вынеси за счёт next и helmet, а 1 a11y пока вынеси как компонент button.a11y.ts
