### ISSUE TITLE
Font loader

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#354]
### С чем связан запрос на фичу?

Загрузка шрифтов с помощью темы

### Расскажите как вы это себе видите

`ui/theme/fonts` - директория с шрифтами (.woff, .woff2)

Должна быть возможность добавить в глобальные стили `@font-face` с урлом до шрифтов

Проблема заключается в том, что директория с шрифтами - не модуль, и при установке `@ui/theme` как зависимость (например в `@landing/app`) появляется проблема с резолвом путей, т.к. напрямую require не работает

**Comment by TorinAsakura** [comment]
@TFK70 контекст только wordpress? или вообще?

**Comment by TFK70** [comment]
@TorinAsakura вообще

**Comment by TorinAsakura** [comment]
@TFK70 а ты на гитхабе уже смотрел экземплы?

**Comment by TFK70** [comment]
@TorinAsakura нет, попробую

**Comment by TFK70** [comment]
https://github.com/atls/uikit/blob/master/ui-proto/theme/src/global.styles.tsx#L8

**Comment by TorinAsakura** [comment]
import { injectGlobal } from 'emotion'

const fontFace = (family, type, weight, style = 'normal') => {
  const fsFamily = family.toLowerCase()
  const fsType = type.toLowerCase()

  return {
    '@font-face': {
      fontFamily: family,
      fontWeight: weight,
      fontStyle: style,
      src: `local('${family}-${type}'),
          url('${require(`../fonts/${fsFamily}/${fsType}/${family}_${type}.woff`)}') format('woff'),
          url('${require(`../fonts/${fsFamily}/${fsType}/${family}_${type}.woff2`)}') format('woff2')`,
    },
  }
}

export const injectFontFaces = (fontFaces = []) =>
  fontFaces.forEach(({ family, type, weight }) => {
    try {
      injectGlobal(fontFace(family, type, weight))
    } catch (error) {
      console.log(error) // eslint-disable-line
    }
  })

**Comment by TFK70** [comment]
@TorinAsakura 

Мы не можем обращаться к файлу с шрифтом как к js модулю

```javascript
error - ../../../../.yarn/__virtual__/@ui-theme-virtual-d8c857aa2a/1/ui/theme/fonts/Gilroy/Bold/Gilroy-Bold.woff
Module parse failed: Unexpected character '' (1:4)
```

Использовать require() (или подобное) - самый простой и надежный вариант включить файл в бандл и не заморачиваться насчет обращения к нему, но то, так как это реализовано сейчас - работать не будет

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> Мы не можем обращаться к файлу с шрифтом как к js модулю
> 
> ```js
> error - ../../../../.yarn/__virtual__/@ui-theme-virtual-d8c857aa2a/1/ui/theme/fonts/Gilroy/Bold/Gilroy-Bold.woff
> Module parse failed: Unexpected character '' (1:4)
> ```
> 
> Использовать require() (или подобное) - самый простой и надежный вариант включить файл в бандл и не заморачиваться насчет обращения к нему, но то, так как это реализовано сейчас - работать не будет

"next-fonts": "1.0.3" - эта версия точно должна работать
