### ISSUE TITLE
Переработать Select

### ISSUE THREAD

**Issue by ikorol3107** [atls/uikit#380]
### Какого рода задача?

Добавить возможность делать тень у дропдауна селекта

### Что и где будем менять?

Добавить ShadowProps  из Styles-system в SelectProps

### Укажите референс

В связи с чем было принято решение? Ссылка на другую задачу, ПР, в общем – нужен контекст

https://github.com/YouThinkResearch/web/pull/583#pullrequestreview-786916887

**Comment by TFK70** [comment]
### Select нужно разбить на parts

**Зачем?** - Это даст более удобный, гибкий и упорядоченный API
**Как это работает сейчас?** - Вся возможная конфигурация селекта регулируется через пропсы:

```javascript
<Select 
   hoverBackgroundColor='red'
   hoverFontColor='white'
   ...+100500 props
/>
```

Как я уже упомянул, это совсем не гибко. Если нам нужно добавить какой-то необычный стиль и тп  - у нас не получится это сделать пока мы не добавим соответствующий проп. С селектом возможно работать только на верхнем уровне, чего очень часто бывает недостаточно (из недавних случаев - не удалось добавить тень для дропдауна). Плюс, работать с компонентом с таким количеством пропов - банально трудно и некомфортно.
