### ISSUE TITLE
Block scroll

### ISSUE THREAD

**Issue by TorinAsakura** [atls/uikit#397]
### С чем связан запрос на фичу?

На некоторой части наших ресурсов используется подход к взаимодействию пользователя с контентом "block scroll"

### Расскажите как вы это себе видите

[Usecase](https://www.figma.com/file/hVmJam0jzM9J4Q651e0urR/Youthink-%7C-Landing-page?node-id=11%3A277)

### Приложите примеры реализаций

https://alvarotrigo.com/fullPage/ru/

**Comment by TorinAsakura** [comment]
@TFK70 на тебе сбор требований/фильтрация по fullpage.js

**Comment by TFK70** [comment]
### Требования

Основное требование -  у page scroll должна быть возможность работать внутри конкретного блока (contain), [демо](https://vikliegostaiev.github.io/react-page-scroller/#/demos/contain) либы которая это поддерживает

### fullpage.js

**Что нужно будет допилить**

Тот самый contain: фуллпейдж умеет работать только на всю страницу полностью, так что эти стили нужно изолировать в рамках родителя, где маунтится Fullpage Wrapper (про fulpage react wrapper можно посмотреть [тут](https://alvarotrigo.com/react-fullpage/#page1))

**Что можно взять**

1. Сам функционал пейдж скролла. Либа поддерживает свайпы, a11y, кроссбраузерность и все такое
2. Контролсы. Триггерить скролл можно по нажатию на кнопку, плюс отображать прогресс - в либе это делается с помощью объекта fullpageApi:
(код из доки)
```javascript
const FullpageWrapper = fullpageProps => (<ReactFullpage
  {...fullpageProps}
  render={({ state, fullpageApi }) => {
    return (HTML_HERE);
  }}
/>);
```

### Более наглядно про то, почему чистый fullpage.js нам не подходит (даже с react wrapper'ом из коробки)

Представление разметки лендинга:

<details>

Блоки идут в таком порядке:

|Hero|
|:---|
|Info|
|About|

Внутри блока Info у нас есть блок, где нам нужен page scroll. Соответственно, там ты маунтим Fullpage wrapper.

</details>

Результат:

https://user-images.githubusercontent.com/62806448/158622100-ca6dc446-af51-4c56-8cfe-01b346806a55.mov

Скролл блокируется на странице полностью, возможности пролистать ниже у нас нет

**Comment by TorinAsakura** [comment]
@monstrs ping
