### ISSUE TITLE
Закончить ui-proto

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#416]
### С чем связан запрос на фичу?

Написать `ui-proto` для всех компонентов в `ui-parts` требующих этого

### Расскажите как вы это себе видите

**Список:**

- [x] autocomplete
- [x] checkbox
- [x] datepicker
- [x] image
- [x] progress
- [x] select
- [x] sidebar
- [x] switch
- [x] tooltip
- [x] upload

**Comment by TFK70** [comment]
@taqyon пока не в процессе, не приоритетный

**Comment by TFK70** [comment]
Прото для остальных компонентов пойдут в процесс после миграции на stitches

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@carminio пройдись по пакетам которые не отмечены

Некоторые из них может понадобиться переписать, под некоторые из них уже вполне можно писать прото. Нужен список, в общем
