### ISSUE TITLE
Очистка кастомного инпута у datepicker

### ISSUE THREAD

**Issue by brusselboy** [atls/uikit#418]
### Описание бага

При нажатии на крестик для очистки инпута, ничего не происходит 

### Воспроизведение

Шаги для воспроизведения бага:

1. `yarn workspace @atls-ui-parts/design dev`
2. В сторибуке выбрать компонент дейтпикера
3. Нажимаем на крестик, видим что инпут не очищается

### Ожидаемое поведение

Нажал на крестик, инпут очистился

### Пример реализации

[пример](https://github.com/YouThinkResearch/web/blob/master/ui/datepicker/src/datepicker.component.tsx)

### Решение проблемы

В кастомный инпут прокинуть startDate и сделать проверку что он не пустой. [пример](https://github.com/YouThinkResearch/web/blob/master/ui/datepicker/src/datepicker.component.tsx#L26-L27)

### Данные окружения

- OS и версия `Ubuntu@22.04`
- Браузер и версия `Chrome@101`

**Comment by TFK70** [comment]
@brusselboy тут же нечего делать в uikit

Когда ты кликаешь на крестик срабатывает onChange, где выбранная дата будет равняться  `null`. Вся логика прописывается снаружи, поэтому она и находится в сторизе

Или я н прав?

**Comment by brusselboy** [comment]
@TFK70 Просто когда кликаешь на крестик ожидаешь что инпут очистится, но никакой реакции не происходит. Проще говоря в сторизе не прописана логика у кастомного инпута, из-за этого и не очищается

p.s обновил ссылки в задаче
