### ISSUE TITLE
Почистить все пакеты и тэги

### ISSUE THREAD

**Issue by TorinAsakura** [atls/uikit#427]
### Какого рода задача?

Наводим порядок

### Что и где будем менять?

Тэги и пакеты

### Укажите референс

Приводим репу к релизному виду. Снести нужно все пакеты и тэги кроме рабочих v1, v2

**Comment by TFK70** [comment]
На будущее для тегов:

```bash
git tag -l | grep -wv 'v1' | grep -wv 'v2' | xargs -L1 git push --delete origin $1
```
