### ISSUE TITLE
Readme cover, или ковер для проекта

### ISSUE THREAD

**Issue by taqyon** [atls/uikit#429]
Нужен ковер для ридми файла. 

<details>
<summary>Примеры</summary>

<img width="899" alt="Снимок экрана 2022-06-29 в 14 14 39" src="https://user-images.githubusercontent.com/14002721/176423723-1a9ef9c3-9422-4bd7-b566-15e1fc8d5855.png">
<img width="866" alt="Снимок экрана 2022-06-29 в 14 14 31" src="https://user-images.githubusercontent.com/14002721/176423737-e75bcde2-74e5-4ad9-a16a-a115d25f4b9d.png">

</details>

По сути здесь два варианта: 
1. Изображение с полной заливкой, грубо говоря прямоугольник
2. Изображение-лого, без фона (в примере есть, Bootstrap)

Так как нет ни названия ни логотипа, нужно и то и другое.

**Comment by TorinAsakura** [comment]
А для кого таска-то?

**Comment by taqyon** [comment]
> А для кого таска-то?

для меня

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
Кавер появился
