### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by taqyon** [atls/uikit#437]
Версионирование. Абзац про то, что мы используем semver, бла бла. Ни укого из примеров кроме bootstrap'a этой секции нет. Нам она нужна? 

## Versioning

For transparency into our release cycle and in striving to maintain backward compatibility, Bootstrap is maintained under [the Semantic Versioning guidelines](https://semver.org/). Sometimes we screw up, but we adhere to those rules whenever possible.

See [the Releases section of our GitHub project](https://github.com/twbs/bootstrap/releases) for changelogs for each release version of Bootstrap. Release announcement posts on [the official Bootstrap blog](https://blog.getbootstrap.com/) contain summaries of the most noteworthy changes made in each release.

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
@TorinAsakura 

Раз уж Hyperion относится к нашей инфраструктуре - предлагаю приложить сюда ссылку на страницу в конвенции, так как семвер у нас используется везде. Не вижу смысла дублировать эту инфу

**Comment by atls-github** [comment]
Статус?

**Comment by TFK70** [comment]
Поступим [так](https://github.com/atls/uikit/issues/437#issuecomment-1296504843), закрою как добавим абзац

**Comment by TorinAsakura** [comment]
> Поступим [так](https://github.com/atls/uikit/issues/437#issuecomment-1296504843), закрою как добавим абзац

ну так добавь же уже, если это абзац чож ты не добавил его за 2 недели-то? Иди добавляй. Закрываю.
