### ISSUE TITLE
Добавить исполняемый файл для генераторов

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#451]
### С чем связан запрос на фичу?

Упростить исполнение скрипта генераторов добавив исполняемый файл

Это позволит избавиться от [тсконфигов](https://github.com/torin-asakura/VSBLE/blob/master/ui/button/tsconfig.generate.json) и прочей "[перегрузки](https://github.com/torin-asakura/VSBLE/blob/master/ui/button/package.json#L6)" при исполнении скрипта с генерацией

### Расскажите как вы это себе видите

`.js` скрипт отвечающий за генерацию должен быть помещен в [bin](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bin)

**Comment by brusselboy** [comment]
## Не генерится файл со стилями

@TFK70 

### Описание
Опубликовал [пакет](https://www.npmjs.com/package/@brusselboy/button), вот [bin](https://github.com/brusselboy/salutation/blob/master/generators/button/package.json#L7), чтобы проверить работает или нет, поставил его в орбитто - в `@ui/button`, там создал такой же [файл](https://github.com/torin-asakura/VSBLE/blob/master/ui/button/src/button.generator.ts) генератора, после делаю `yarn workspace @ui/button generate-button-styles` команда выполняется, но ничего не происходит. Чтобы убедиться работает ли вообще генерация, добавил тсконфиг и скрипт в package.json как в vsble, запустил скрипт и появился файл со стилями.

### Вопрос
 Что необходимо сделать дальше, чтобы файл генерился именно через `yarn workspace @ui/button generate-button-styles`?

**Comment by brusselboy** [comment]
> @brusselboy если скрипт действительно исполняется - то проблема в релятивных путях, видимо. Тебе нужно выстраивать путь до файла отталкиваясь от `process.cwd`, это путь до директории, в которой скрипт был вызван
> 
> Вообще тебе нужно подебажить это делай - поконсоль путь в который у тебя пишется файл

А на какой файл в итоге нужно ориентироваться? в bin нужно указать путь до `dist/index.js`? Ведь он же является исполняемым?

**Comment by TFK70** [comment]
@brusselboy а откуда я знаю какой файл у тебя там исполняемый? В текущем пакете генератора его нет, его нужно добавить, потому что до этого мы этот файл писали руками на проектах

Ты точно задачу понял?

**Comment by TFK70** [comment]
@carminio нужно сделать то же самое для `@atls-ui-generators/input`
