### ISSUE TITLE
Extending stylization of flex components

### ISSUE THREAD

**Issue by carminio** [atls/uikit#461]
# Сводка

Вношу предложение расширить стилизацию флекс компонентов (Box, Row, etc) добавив `columnGap` и `rowGap`

# Базовый пример

<details>

Без `columnGap`

```tsx
 <Row justifyContent='flex-start' flexWrap='wrap'>
        {items.map((title) => (
          <Box
            minWidth={[61, 61, 73]}
            onClick={() => {
              setSelectedItem(title)
            }}
          >
            <Radio checked={selectedItem === title} textTransform='uppercase'>
              {title}
            </Radio>
            <Layout flexBasis={[12, 12, 12]} flexShrink={0} />
          </Box>
        ))}
  </Row>
```

C `columnGap`

```tsx
  <Row style={{ columnGap: 12 }} justifyContent='flex-start' flexWrap='wrap'>
        {items.map((title) => (
          <Box
            minWidth={[49, 49, 61]}
            onClick={() => {
              setSelectedItem(title)
            }}
          >
            <Radio checked={selectedItem === title} textTransform='uppercase'>
              {title}
            </Radio>
          </Box>
        ))}
      </Row>
```

</details>

# Мотивация

Удобство и простота в использовании

# Дизайн в деталях

Больше не будет необходимости, например, когда мапишь какой-то список айтемов, добавлять отступы в виде `<Layout flexBasis={[12, 12, 12]} flexShrink={0} />` из-за которого также нужно увеличивать ширину самого элемента (в примере выше можно увидеть что у Box minWidth отличается, при использовании flexBasis приходится увеличивать width т.к flexBasis тоже занимает место). 

Да и вообще в целом можно избежать использования Layout с flexBasis, частый кейс это когда нужно со всех сторон сделать отступы, слева справа сверху снизу, и для всего этого юзаем flexBasis и в таком кейсе будет четыре Layout, хотя можно было бы обойтись написав один раз `columnGap` и `rowGap`

# Недостатки

Сейчас сложно сказать какой недостаток у этого решения, если бы я составлял этот RFC год назад, написал бы что поддерживается не всеми браузерами, но сейчас ситуация следующая:
<details>

<img width="781" alt="image" src="https://user-images.githubusercontent.com/35490768/197974546-821feedf-75d8-4fe2-8dd1-c0b42cc8bbe9.png">

</details>

# Альтернативы

-

# Стратегия адаптации

Ничего не пострадает, на проектах можно оставить и текущее решение, на новых юзать новое

# Как мы будем этому обучать

Также как и с использованием flexBasis, только с этим решением будет еще проще

**Comment by TFK70** [comment]
@carminio я думаю это идёт немного вразрез нашим подходам по проектированию ui

Суть в том, что всё, на чём строится наш ui - это сущности, включая отступы. Это основная причина почему мы, например, не используем паддинги и маржины:

**Пример без маржинов:**

```shell
<Компонент1>
<Отступ 12px>
<Компонент2>
```

Предсказуемо, между двумя компонентами есть отступ 12px - это явно видно в коде и будет явно видно в DOM. Отступ 12px можно будет выделить - это отдельный блок, отдельная сущность

**Пример с маржинами:**

```shell
<Компонент1>
<Компонент2>
```

Здесь вообще может существовать несколько вариантов:

- Компонент1 имеет `marginBottom: 12px`
- Компонент2 имеет `marginTop: 12px`
- И Компонент1, и Компонент2 имеют по маржину, которые в сумме дают 12px
- Отступа между компонентами может вообще не быть

Это и называется непредсказуемостью: ты смотришь на код или на дерево в доме и не можешь чётко сказать как ведёт себя тот или иной элемент, пока детально не изучишь его стили.

Когда ты гасишь отступы с флекс базисами подобным образом, твой код может и будет выглядеть чуть попроще, и писаться возможно будет чуть быстрее, но ты таким образом будешь превращать его в чёрный ящик, в котором со временем сам разобраться не сможешь

Тем не менее, если это действительно такая проблема с мапом колонок - проблему можно решить другим способом: сделай компонент, который будет создавать Layout с flexBasis под капотом (а-ля `<Repeater />`)

**Comment by atls-github** [comment]
Статус?
